### ISSUE TITLE
ABA problem in stack

### ISSUE THREAD

**Issue by R-omk** [PurpureGecko/go-lfc#1]
At first sight your stack with typical ABA problem 
[https://en.wikipedia.org/wiki/ABA_problem](
https://en.wikipedia.org/wiki/ABA_problem)

Please, check the correctness of the algorithm.

**Comment by PurpureGecko** [comment]
This problem not correct for Go. Every time when I Push value I create new  `Element`, and this element can't be with pointer like another one used in another thread. So, there are not second A.
